### ISSUE TITLE
Changing the name of the team on github breaks things

### ISSUE THREAD

**Issue by brycefisher** [trevoro/sshauth#3]
So, I'm using this tool in development. However, someone changed the name of the team on github from what is in the config file and suddenly no ssh works :-/

I'd like to submit a PR that allows an optional TeamID field and makes the existing Team field optional. If TeamID is provided, we can skip the API call to organizations list teams. Otherwise, it would work the same as now.

Would you be willing to accept such a PR?

**Comment by brycefisher** [comment]
:bump: Just checking if there's any movement on this issue. I'd love to write a small patch for this, but only if you'll accept it. Thanks!

**Comment by trevoro** [comment]
Hey @brycefisher - totally willing to accept a patch for that issue.
In the meantime it _should_ fall back on your `~/.ssh/authorized_keys` file but if that's not working either we can address that together as a separate issue.

👍

**Comment by brycefisher** [comment]
Thanks @trevoro ! It absolutely does fallback to the authorized_keys file. 

I'll try to submit a PR for this fix in the next day or two. Much appreciated!!

**Comment by brycefisher** [comment]
Woot!!
